<?php

$tecnologia = ['computador', 'informática', 'software', 'hardware', 'programação', 'código', 'sistemas', 'algoritmo', 'rede', 'servidor',
'banco de dados', 'nuvem', 'cloud', 'frontend', 'backend', 'fullstack', 'javascript', 'python', 'php', 'java',
'html', 'css', 'git', 'github', 'linux', 'windows', 'dados', 'inteligência artificial', 'machine learning', 'deep learning',
'api', 'web', 'mobile', 'aplicativo', 'tecnologia', 'digital', 'inovação', 'devops', 'agile', 'scrum',
'automação', 'sistemas embarcados', 'iot', 'cibersegurança', 'criptografia', 'firewall', 'vpn', 'cloud computing', 'big data', 'análise de dados',
'ciência de dados', 'engenharia de software', 'desenvolvimento', 'interface', 'usuário', 'ux', 'ui', 'processador', 'memória', 'armazenamento',
'computação', 'rede neural', 'robot', 'robótica', 'tecnólogo', 'suporte técnico', 'manutenção', 'eletrônica', 'framework', 'typescript',
'react', 'vue', 'angular', 'bootstrap', 'node', 'express', 'laravel', 'django', 'flask', 'mobile first',
'responsivo', 'teclado', 'mouse', 'tela', 'monitor', 'modem', 'wifi', 'bluetooth', 'conectividade', 'sinal',
'streaming', 'game', 'gamer', 'vr', 'realidade virtual', 'metaverso', 'blockchain', 'bitcoin', 'token', 'criptomoeda','codigo', 'programar', 'programando', 'codar', 'codando', 'debuggar', 'debugando', 'compilar', 'compilando', 'executar',
    'executando', 'testar', 'testando', 'depurar', 'depurando', 'implementar', 'implementando', 'desenvolver', 'desenvolvendo',
    'configurar', 'configurando', 'instalar', 'instalando', 'atualizar', 'atualizando', 'conectar', 'conectando', 'processar',
    'processando', 'armazenar', 'armazenando', 'criptografar', 'criptografando', 'hackear', 'hackeando', 'navegar', 'navegando',
    'baixar', 'baixando', 'subir', 'subindo', 'deployar', 'deployando', 'commit', 'comitando', 'push', 'pushando',
    'pull', 'pullando', 'merge', 'mergeando', 'branch', 'brancheando', 'fork', 'forkando', 'clone', 'clonando',
    'hostear', 'hosteando', 'cloud', 'cloudeando', 'backup', 'backupeando', 'restaurar', 'restaurando', 'monitorar', 'monitorando',
    'otimizar', 'otimizando', 'escalar', 'escalando', 'virtualizar', 'virtualizando', 'containerizar', 'containerizando', 'logar', 'logando',
    'buildar', 'buildando', 'debbugar', 'debbugando', 'refatorar', 'refatorando', 'integrar', 'integrando', 'versionar', 'versionando',
    'documentar', 'documentando', 'automatizar', 'automatizando', 'scannear', 'scanneando', 'parsear', 'parseando', 'renderizar', 'renderizando'
];

$saude = ['saúde', 'hospital', 'médico', 'enfermeiro', 'enfermeira', 'enfermagem', 'clínica', 'remédio', 'medicamento', 'doença',
'vacina', 'tratamento', 'cura', 'cirurgia', 'sintoma', 'diagnóstico', 'exame', 'laboratório', 'ambulatorial', 'emergência',
'primeiros socorros', 'UTI', 'fisioterapia', 'psicologia', 'nutrição', 'nutricionista', 'terapia', 'terapeuta', 'cardiologista', 'pediatra',
'ortopedista', 'oncologista', 'infectologista', 'anestesia', 'anestesiologia', 'pressão', 'glicose', 'colesterol', 'pulmão', 'coração',
'rim', 'fígado', 'ossos', 'coluna', 'câncer', 'covid', 'gripe', 'resfriado', 'febre', 'dor',
'saúde pública', 'saúde mental', 'autoestima', 'atividade física', 'dieta', 'alimentação', 'obesidade', 'sedentarismo', 'higiene', 'vacinação',
'pandemia', 'epidemia', 'vírus', 'bactéria', 'fungo', 'infecção', 'inflamação', 'cura', 'prevenção', 'prognóstico',
'tratamento', 'internação', 'hospitalar', 'ambulância', 'oxigênio', 'soro', 'injeção', 'agulha', 'consulta', 'prontuário',
'farmácia', 'farmacêutico', 'biomedicina', 'enfermidade', 'genética', 'sangue', 'hemograma', 'plano de saúde', 'psiquiatria', 'autoexame',
'mamografia', 'papanicolau', 'oncologia', 'hepatite', 'aids', 'DST', 'pneumonia', 'asma', 'bronquite', 'imunização', 'comer', 'comendo', 'ingerir', 'ingerindo', 'alimentar', 'alimentando', 'digerir', 'digerindo', 'nutrir', 'nutrindo',
    'beber', 'bebendo', 'hidratar', 'hidratando', 'exercitar', 'exercitando', 'malhar', 'malhando', 'correr', 'correndo',
    'nadar', 'nadando', 'saltar', 'saltando', 'alongar', 'alongando', 'respirar', 'respirando', 'meditar', 'meditando',
    'dormir', 'dormindo', 'descansar', 'descansando', 'curar', 'curando', 'sarar', 'sarando', 'tratar', 'tratando',
    'medicar', 'medicando', 'operar', 'operando', 'suturar', 'suturando', 'diagnosticar', 'diagnosticando', 'examinar', 'examinando',
    'vacinar', 'vacinando', 'prevenir', 'prevenindo', 'reabilitar', 'reabilitando', 'fisioterapeutizar', 'fisioterapeutizando', 'psicologar', 'psicologando',
    'enfermeirar', 'enfermeirando', 'medicar', 'medicando', 'hospitalizar', 'hospitalizando', 'internar', 'internando', 'recuperar', 'recuperando',
    'recaída', 'recaidando', 'convalescer', 'convalescendo', 'palpar', 'palpando', 'auscultar', 'auscultando', 'injetar', 'injetando',
    'sangrar', 'sangrando', 'transfundir', 'transfundindo', 'transplantar', 'transplantando', 'reanimar', 'reanimando', 'ressuscitar', 'ressuscitando']
;

$design = ['design', 'gráfico', 'visual', 'estética', 'cor', 'tipografia', 'ilustração', 'desenho', 'layout', 'composição',
'proporção', 'vetor', 'bitmap', 'photoshop', 'illustrator', 'corel draw', 'figma', 'adobe', 'paleta', 'forma',
'contraste', 'harmonia', 'interface', 'ux', 'ui', 'produto', 'design thinking', 'prototipagem', 'mockup', 'wireframe',
'user flow', 'branding', 'identidade visual', 'marca', 'logotipo', 'ícone', 'banner', 'panfleto', 'folder', 'cartaz',
'flyer', 'webdesign', 'design digital', 'motion', 'animação', '2d', '3d', 'layout responsivo', 'infografia', 'embalagem',
'rótulo', 'editorial', 'revista', 'livro', 'capa', 'diagramação', 'publicidade', 'marketing visual', 'portfólio', 'estilo',
'realismo', 'minimalismo', 'simetria', 'assimetria', 'linha', 'curva', 'esboço', 'raster', 'canvas', 'grid',
'projeto gráfico', 'criatividade', 'inspiração', 'conceito', 'desenvolvimento visual', 'flat design', 'design system', 'fontes', 'pixels', 'dpi',
'resolução', 'software de edição', 'imagem', 'escala', 'proporção áurea', 'direção de arte', 'foco', 'equilíbrio', 'moderno', 'retrô',
'vintage', 'icônico', 'identidade', 'manual de marca', 'grafismo', 'direção', 'estampa', 'adesivo', 'mock', 'aplicação','desenhar', 'desenhando', 'esboçar', 'esboçando', 'ilustrar', 'ilustrando', 'colorir', 'colorindo', 'pintar', 'pintando',
    'rabiscar', 'rabiscando', 'diagramar', 'diagramando', 'compor', 'compondo', 'fotografar', 'fotografando', 'editar', 'editando',
    'retocar', 'retocando', 'recortar', 'recortando', 'colar', 'colando', 'vetorizar', 'vetorizando', 'renderizar', 'renderizando',
    'animar', 'animando', 'prototipar', 'prototipando', 'mockar', 'mockando', 'wireframar', 'wireframando', 'brandear', 'brandeando',
    'logotipar', 'logotipando', 'iconizar', 'iconizando', 'bannerizar', 'bannerizando', 'cartazear', 'cartazeando', 'panfletar', 'panfletando',
    'embalar', 'embalando', 'rotular', 'rotulando', 'revistear', 'revisteando', 'capa', 'capando', 'diagramar', 'diagramando',
    'publicitariar', 'publicitariando', 'marketear', 'marketeando', 'portfoliar', 'portfolioando', 'estilizar', 'estilizando', 'minimalizar', 'minimalizando',
    'simetrizar', 'simetrizando', 'assimetrizar', 'assimetrizando', 'linhear', 'linheando', 'curvar', 'curvando', 'rasterizar', 'rasterizando',
    'canva', 'canvando', 'grade', 'gradeando', 'criar', 'criando', 'inspirar', 'inspirando', 'conceituar', 'conceituando',
    'flat', 'flateando', 'fontar', 'fontando', 'pixelar', 'pixelando', 'resolver', 'resolvendo', 'escalar', 'escalando']
;
$artes = ['arte','artes', 'artista', 'pintura', 'escultura', 'teatro', 'dança', 'música', 'performance', 'instalação', 'aquarela',
'acrílica', 'óleo sobre tela', 'grafite', 'arte urbana', 'desenho','desenhando', 'cinema', 'fotografia', 'poesia', 'literatura', 'novela',
'roteiro', 'drama', 'comédia', 'trágico', 'tragédia', 'expressão', 'emoção', 'criatividade', 'performance', 'palco',
'ator', 'atriz', 'roteirista', 'diretor', 'curadoria', 'exposição', 'galeria', 'museu', 'vernissage', 'portfólio',
'ensaio', 'figurino', 'cenário', 'luz', 'iluminação', 'som', 'voz', 'interpretação', 'mímica', 'estética',
'sensibilidade', 'imaginação', 'retrato', 'paisagem', 'abstrato', 'moderno', 'contemporâneo', 'clássico', 'barroco', 'renascentista',
'expressionismo', 'cubismo', 'surrealismo', 'impressionismo', 'realismo', 'vanguarda', 'arte digital', 'ilustração', 'graffiti', 'cerâmica',
'colagem', 'bordado', 'fanzine', 'história da arte', 'estética', 'beleza', 'visual', 'poético', 'composição', 'técnica',
'observação', 'modelo vivo', 'oficina', 'estúdio', 'residência artística', 'movimento artístico', 'livro de artista', 'poema visual', 'happening', 'performance art','pintar', 'pintando', 'esculpir', 'esculpindo', 'teatrar', 'teatrando', 'dançar', 'dançando', 'musicar', 'musicando',
    'performar', 'performando', 'instalar', 'instalando', 'aquarelar', 'aquarelando', 'acrilizar', 'acrilizando', 'olear', 'oleando',
    'grafitar', 'grafitando', 'urbanizar', 'urbanizando', 'desenhar', 'desenhando', 'cinematografar', 'cinematografando', 'fotografar', 'fotografando',
    'poetizar', 'poetizando', 'literaturar', 'literaturando', 'novelar', 'novelando', 'roteirizar', 'roteirizando', 'dramatizar', 'dramatizando',
    'comediografar', 'comediografando', 'tragicar', 'tragicando', 'expressar', 'expressando', 'emocionar', 'emocionando', 'criar', 'criando',
    'palcar', 'palcando', 'atorar', 'atorando', 'atrizar', 'atrizando', 'roteirizar', 'roteirizando', 'diretorear', 'diretoreando',
    'curatorar', 'curatorando', 'expor', 'expondo', 'galeriar', 'galeriando', 'musealizar', 'musealizando', 'vernissar', 'vernissando',
    'portfoliar', 'portfolioando', 'ensaiar', 'ensaiando', 'figurinar', 'figurinando', 'cenografar', 'cenografando', 'luzir', 'luzindo',
    'iluminar', 'iluminando', 'sonorizar', 'sonorizando', 'vozear', 'vozeando', 'interpretar', 'interpretando', 'mimar', 'mimando']
;
$engenharia = ['engenharia', 'projeto', 'física', 'matemática', 'estrutura', 'cálculo', 'materiais', 'concreto', 'aço', 'cimento',
'construção', 'civil', 'elétrica', 'mecânica', 'química', 'industrial', 'produção', 'robótica', 'automação', 'sistemas',
'termodinâmica', 'resistência', 'vibração', 'hidráulica', 'pneumática', 'instalação', 'execução', 'planejamento', 'orçamento', 'frota',
'obras', 'manutenção', 'diagrama', 'circuito', 'engenheiro', 'projeto estrutural', 'AVCB', 'autoCAD', 'solidworks', 'PLC',
'controle', 'produção', 'planta', 'técnico', 'inovação', 'eficiência', 'processo', 'análise estrutural', 'normas técnicas', 'ABNT',
'medição', 'nivelamento', 'topografia', 'levantamento', 'fundações', 'cimento armado', 'obra civil', 'alvenaria', 'edificação', 'engenharia ambiental',
'recursos hídricos', 'drenagem', 'pavimentação', 'viaduto', 'ponte', 'logística', 'custo', 'máquina', 'equipamento', 'traço de concreto',
'energia', 'usina', 'gerador', 'reator', 'turbo', 'pressão', 'vazão', 'escoamento', 'desenho técnico', 'engenharia de tráfego',
'fluxo', 'mapa', 'GPS', 'levantamento planialtimétrico', 'cadastro técnico', 'simulação', 'teste', 'protótipo', 'desenvolvimento', 'calibração','engenhar', 'engenhando', 'projetar', 'projetando', 'fisicar', 'fisicando', 'matematizar', 'matematizando', 'estruturar', 'estruturando',
    'calcular', 'calculando', 'materializar', 'materializando', 'concretar', 'concretando', 'açar', 'açando', 'cimentar', 'cimentando',
    'construir', 'construindo', 'civilizar', 'civilizando', 'eletrizar', 'eletrizando', 'mecanizar', 'mecanizando', 'quimicar', 'quimicando',
    'industrializar', 'industrializando', 'produzir', 'produzindo', 'robotizar', 'robotizando', 'automatizar', 'automatizando', 'sistematizar', 'sistematizando',
    'termodinamicar', 'termodinamicando', 'resistir', 'resistindo', 'vibrar', 'vibrando', 'hidraulicar', 'hidraulicando', 'pneumatizar', 'pneumatizando',
    'instalar', 'instalando', 'executar', 'executando', 'planejar', 'planejando', 'orçar', 'orçando', 'frotar', 'frotando',
    'obrar', 'obrando', 'manter', 'mantendo', 'diagramar', 'diagramando', 'circuitar', 'circuitando', 'engenheirar', 'engenheirando',
    'projetar', 'projetando', 'avcbar', 'avcbando', 'autocadar', 'autocadando', 'solidworkar', 'solidworkando', 'plcar', 'plcando',
    'controlar', 'controlando', 'produzir', 'produzindo', 'plantar', 'plantando', 'técnico', 'técnicando', 'inovar', 'inovando']
;
$esportes = ['esporte', 'futebol', 'basquete', 'vôlei', 'handebol', 'tênis', 'corrida', 'natação', 'ciclismo', 'musculação',
'goleiro', 'atacante', 'meio-campo', 'defesa', 'jogador', 'treinador', 'técnico', 'partida', 'torcida', 'ginásio',
'estádio', 'arena', 'chute', 'passe', 'drible', 'gol', 'ponto', 'placar', 'campeonato', 'competição',
'olimpíada', 'maratona', 'triatlo', 'crossfit', 'alongamento', 'aquecimento', 'treinamento', 'condicionamento', 'resistência', 'força',
'agilidade', 'velocidade', 'coletivo', 'individual', 'arremesso', 'corrida de rua', 'bicicleta', 'bola', 'quadra', 'campo',
'rugby', 'críquete', 'beisebol', 'boxe', 'luta', 'karatê', 'judo', 'mma', 'jiu-jitsu', 'escalada',
'skate', 'surf', 'esqui', 'snowboard', 'golfe', 'pesca esportiva', 'automobilismo', 'motociclismo', 'kart', 'remo',
'canoagem', 'dança esportiva', 'patinação', 'ginástica', 'saltos', 'barreiras', 'jogo', 'arbitragem', 'regra', 'uniforme',
'clube', 'liga', 'divisão', 'título', 'medalha', 'recorde', 'fair play', 'lesão', 'recuperação', 'fisioterapia esportiva','esportear', 'esporteando', 'futebolar', 'futebolando', 'basquetear', 'basqueteando', 'volear', 'voleando', 'handebolar', 'handebolando',
    'tenizar', 'tenizando', 'correr', 'correndo', 'nadar', 'nadando', 'ciclizar', 'ciclizando', 'muscular', 'musculando',
    'golear', 'goleando', 'atacar', 'atacando', 'meio-campo', 'meio-campando', 'defender', 'defendendo', 'jogar', 'jogando',
    'treinar', 'treinando', 'técnico', 'técnicando', 'partidar', 'partidando', 'torcer', 'torcendo', 'ginasiar', 'ginasiando',
    'estadiar', 'estadiando', 'arenar', 'arenando', 'chutar', 'chutando', 'passar', 'passando', 'driblar', 'driblando',
    'golear', 'goleando', 'pontuar', 'pontuando', 'placar', 'placando', 'campeonar', 'campeonando', 'competir', 'competindo',
    'olimpiar', 'olimpiando', 'maratonar', 'maratonando', 'triatletar', 'triatletando', 'crossfitear', 'crossfiteando', 'alongar', 'alongando',
    'aquecer', 'aquecendo', 'treinar', 'treinando', 'condicionar', 'condicionando', 'resistir', 'resistindo', 'forçar', 'forçando',
    'agilizar', 'agilizando', 'velocizar', 'velocizando', 'coletivar', 'coletivando', 'individualizar', 'individualizando', 'arremessar', 'arremessando']
;
$ciencias = ['ciência', 'pesquisa', 'experimento', 'hipótese', 'tese', 'teoria', 'prova', 'biologia', 'química', 'física',
'matemática', 'astronomia', 'geografia', 'geologia', 'arqueologia', 'sociologia', 'antropologia', 'psicologia', 'ecologia', 'evolução',
'adaptação', 'espécie', 'molécula', 'átomo', 'partícula', 'matéria', 'energia', 'gravidade', 'massa', 'força',
'química orgânica', 'genética', 'DNA', 'RNA', 'microscópio', 'telescópio', 'laboratório', 'método científico', 'clima', 'solo',
'pH', 'reação', 'combustão', 'solução', 'mistura', 'substância', 'modelo', 'simulação', 'programa', 'estatística',
'probabilidade', 'dados', 'inovação', 'descoberta', 'universo', 'planeta', 'galáxia', 'experiência', 'resultado', 'publicação',
'artigo científico', 'revisão', 'cientista', 'biólogo', 'físico', 'químico', 'matemático', 'astrônomo', 'pesquisador', 'especialista',
'fundamento', 'princípio', 'observação', 'controle', 'variável', 'análise', 'interpretação', 'ensaio', 'modelo atômico', 'tabela periódica',
'elemento', 'hidrogênio', 'oxigênio', 'carboidrato', 'proteína', 'lipídio', 'ácido', 'base', 'sólido', 'líquido', 'cientifizar', 'cientifizando', 'pesquisar', 'pesquisando', 'experimentar', 'experimentando', 'hipotetizar', 'hipotetizando', 'tesear', 'teseando',
    'teorizar', 'teorizando', 'provar', 'provando', 'biologar', 'biologando', 'quimicar', 'quimicando', 'fisicar', 'fisicando',
    'matematizar', 'matematizando', 'astronomar', 'astronomando', 'geografar', 'geografando', 'geologar', 'geologando', 'arqueologar', 'arqueologando',
    'sociologar', 'sociologando', 'antropologar', 'antropologando', 'psicologar', 'psicologando', 'ecologar', 'ecologando', 'evoluir', 'evoluindo',
    'adaptar', 'adaptando', 'especiar', 'especiando', 'molecular', 'moleculando', 'atomizar', 'atomizando', 'particular', 'particulando',
    'materiar', 'materiando', 'energizar', 'energizando', 'gravitar', 'gravitando', 'massar', 'massando', 'forçar', 'forçando',
    'organicar', 'organicando', 'genetizar', 'genetizando', 'dnar', 'dnando', 'rnar', 'rnando', 'microscopar', 'microscopando',
    'telescopar', 'telescopando', 'laboratorar', 'laboratorando', 'metodar', 'metodando', 'climar', 'climando', 'solar', 'solando',
    'phar', 'phando', 'reagir', 'reagindo', 'combustar', 'combustando', 'solucionar', 'solucionando', 'misturar', 'misturando']
;
$linguas = ['idioma', 'língua', 'português', 'inglês', 'espanhol', 'francês', 'alemão', 'italiano', 'japonês', 'chinês',
'russo', 'tradução', 'intérprete', 'leitura', 'escrita', 'fala', 'oralidade', 'vocabulário', 'gramática', 'conjugação',
'verbo', 'substantivo', 'adjetivo', 'advérbio', 'sintaxe', 'pronome', 'expressão', 'pronúncia', 'alfabeto', 'letra',
'leitura crítica', 'compreensão', 'significado', 'dicionário', 'texto', 'frase', 'oração', 'parágrafo', 'pontuação', 'ortografia',
'linguística', 'literatura', 'poesia', 'romance', 'conto', 'crônica', 'ensaio', 'fala', 'discurso', 'retórica',
'tradução simultânea', 'bilingue', 'multilingue', 'idioma nativo', 'fluência', 'aprendizado', 'proficiência', 'interpretação', 'dialeto', 'caligrafia',
'acento', 'linguagem formal', 'linguagem informal', 'regência', 'semântica', 'fonética', 'morfologia', 'sintaxe', 'gíria', 'neologismo',
'comunicação', 'linguagem corporal', 'entonação', 'dicção', 'oral', 'escrito', 'conversação', 'expressar', 'comunicar', 'resumo',
'interlocutor', 'gramática normativa', 'expressão idiomática', 'linguagem figurada', 'verbo auxiliar', 'artigo', 'preposição', 'conjunção', 'tradução juramentada', 'linguagem técnica','idiomar', 'idiomando', 'linguajar', 'linguajando', 'portuguesar', 'portuguesando', 'inglesar', 'inglesando', 'espanholar', 'espanholando',
    'francesar', 'francesando', 'alemaizar', 'alemaizando', 'italianizar', 'italianizando', 'japonesar', 'japonesando', 'chinesar', 'chinesando',
    'russar', 'russando', 'traduzir', 'traduzindo', 'interpretar', 'interpretando', 'ler', 'lendo', 'escrever', 'escrevendo',
    'falar', 'falando', 'oralizar', 'oralizando', 'vocabular', 'vocabulando', 'gramatizar', 'gramatizando', 'conjugar', 'conjugando',
    'verbear', 'verbeando', 'substantivar', 'substantivando', 'adjetivar', 'adjetivando', 'adverbializar', 'adverbializando', 'sintaxar', 'sintaxando',
    'pronomizar', 'pronomizando', 'expressar', 'expressando', 'pronunciar', 'pronunciando', 'alfabetizar', 'alfabetizando', 'letrear', 'letreando',
    'leiturar', 'leiturando', 'compreender', 'compreendendo', 'significar', 'significando', 'dicionarizar', 'dicionarizando', 'textuar', 'textuando',
    'frasear', 'fraseando', 'orar', 'orando', 'paragrafar', 'paragrafando', 'pontuar', 'pontuando', 'ortografar', 'ortografando',
    'linguistizar', 'linguistizando', 'literaturar', 'literaturando', 'poetizar', 'poetizando', 'romancear', 'romanceando', 'contar', 'contando']
;
$administracao = [
  'administração','empresa','gestão','liderança','empreendedorismo','planejamento','estratégia','negócios',
  'finanças','recursos humanos','RH','contabilidade','orçamentos','investimento','logística','produtividade',
  'metas','organização','controle','supervisão','gerente','diretoria','cargo','tomada de decisão','análise SWOT',
  'organograma','departamento','operacional','lucro','prejuízo','faturamento','fluxo de caixa','capital','receita',
  'despesa','mercado','fornecedor','cliente','consumidor','negociação','vendas','estoque','custo','avaliação',
  'desempenho','eficiência','eficácia','reuniões','projetos','consultoria','administração pública','auditoria',
  'compliance','governança','processos','inovação','competitividade','cadeia produtiva','planejamento estratégico',
  'marketing institucional','desenvolvimento organizacional','benchmarking','gestão de pessoas',
  'comportamento organizacional','indicadores','KPIs','plano de ação','matriz BCG','planejamento financeiro',
  'sistema ERP','cadeia de suprimentos','administração financeira','cargo de chefia','analista administrativo',
  'trainee','executivo','plano de carreira','desempenho organizacional','análise de processos',
  'administração de empresas','administração rural','administrador','administração hospitalar','serviços administrativos',
  'área administrativa','contratos','fluxo operacional','cultura organizacional','planejamento de carreira',
  'estrutura organizacional','relatório gerencial','produtividade empresarial','plano de negócios','ética empresarial',
  'compliance fiscal','planejamento tático','liderança corporativa','eficiência operacional', 'administrar', 'administrando', 'empresar', 'empresando', 'gerir', 'gerindo', 'liderar', 'liderando', 'empreender', 'empreendendo',
    'planejar', 'planejando', 'estrategizar', 'estrategizando', 'negociar', 'negociando', 'financiar', 'financiando', 'recursar', 'recursando',
    'rhizar', 'rhizando', 'contabilizar', 'contabilizando', 'orçar', 'orçando', 'investir', 'investindo', 'logistizar', 'logistizando',
    'produzir', 'produzindo', 'metar', 'metando', 'organizar', 'organizando', 'controlar', 'controlando', 'supervisionar', 'supervisionando',
    'gerenciar', 'gerenciando', 'diretoriar', 'diretoriando', 'cargar', 'cargando', 'tomar', 'tomando', 'swotar', 'swotando',
    'organogramar', 'organogramando', 'departamentar', 'departamentando', 'operar', 'operando', 'lucrar', 'lucrando', 'prejudicar', 'prejudicando',
    'faturar', 'faturando', 'fluxar', 'fluxando', 'capitalizar', 'capitalizando', 'receitar', 'receitando', 'despesar', 'despesando',
    'mercado', 'mercando', 'fornecer', 'fornecendo', 'clientear', 'clienteando', 'consumir', 'consumindo', 'negociar', 'negociando',
    'vender', 'vendendo', 'estocar', 'estocando', 'custar', 'custando', 'avaliar', 'avaliando', 'desempenhar', 'desempenhando'
]
;
$marketing = [
  'marketing','publicidade','propaganda','branding','vendas','consumidor','campanha','promoção','anúncio',
  'redes sociais','digital','inbound','outbound','SEO','SEM','tráfego pago','tráfego orgânico','influenciador',
  'persona','público-alvo','funil de vendas','jornada do cliente','estratégia','posicionamento','concorrência',
  'valor percebido','engajamento','conversão','leads','CRM','email marketing','automação','marketing de conteúdo',
  'storytelling','mídia','mídia paga','mídia orgânica','alcance','impressões','visualizações','análise de dados',
  'KPIs','ROI','remarketing','branding emocional','logotipo','identidade visual','slogan','segmentação','targeting',
  'comportamento do consumidor','pesquisa de mercado','lançamento','produto','serviço','experiência do cliente',
  'fidelização','buzz marketing','marketing viral','growth hacking','marketing pessoal','marketing político',
  'análise SWOT','concorrente','reputação','copywriting','call to action','testes A/B','UX','UI','blog','landing page',
  'funil de marketing','conversão de leads','gatilhos mentais','oferta','preço','valor','diferenciação',
  'mídia digital','tráfego','autoridade digital','presença online','canais de distribuição','remarketing dinâmico',
  'CAC','LTV','customer success','brand awareness','marketing de influência','google ads','facebook ads',
  'marketing estratégico','marketing sensorial','performance','storytelling visual','vídeos institucionais',
  'comunicação integrada', 'marketear', 'marketeando', 'publicitar', 'publicitando', 'propagar', 'propagando', 'brandear', 'brandeando', 'vender', 'vendendo',
    'consumir', 'consumindo', 'campanhar', 'campanhando', 'promover', 'promovendo', 'anunciar', 'anunciando', 'socializar', 'socializando',
    'digitalizar', 'digitalizando', 'inboundar', 'inboundando', 'outboundar', 'outboundando', 'seoar', 'seoando', 'semar', 'semando',
    'tráfegar', 'tráfegando', 'pagar', 'pagando', 'organicar', 'organicando', 'influenciar', 'influenciando', 'personar', 'personando',
    'publicar', 'publicando', 'alvo', 'alvando', 'funilar', 'funilando', 'jornadear', 'jornadeando', 'estrategizar', 'estrategizando',
    'posicionar', 'posicionando', 'competir', 'competindo', 'valorizar', 'valorizando', 'engajar', 'engajando', 'converter', 'convertendo',
    'leadear', 'leadeando', 'crmar', 'crmando', 'emailar', 'emailando', 'automatizar', 'automatizando', 'conteudar', 'conteudando',
    'storytelar', 'storytelando', 'mediar', 'mediando', 'pagar', 'pagando', 'organicar', 'organicando', 'alcançar', 'alcançando',
    'imprimir', 'imprimindo', 'visualizar', 'visualizando', 'analisar', 'analisando', 'kpiar', 'kpiando', 'roiar', 'roiando'
]
;
$nutricao = [
  'nutrição','nutricionista','alimentação','dieta','saúde','reeducação alimentar','nutrientes','vitaminas',
  'minerais','calorias','carboidrato','proteína','gordura','fibras','açúcar','colesterol','metabolismo',
  'restrição alimentar','cardápio','plano alimentar','intolerância','glúten','lactose','intolerância à lactose',
  'intolerância ao glúten','insulina','glicose','alimentos naturais','alimentos processados','suplementação',
  'suplementos','whey protein','creatina','ômega 3','fitoterápicos','alimentação balanceada','alimentação saudável',
  'vegetariano','vegano','alimentação vegana','alimentos integrais','orgânicos','conservantes','corantes','aditivos',
  'nutrição esportiva','nutrição clínica','nutrição funcional','nutrição infantil','nutrição hospitalar','nutrição escolar',
  'nutrição coletiva','pirâmide alimentar','rotulagem','leitura de rótulos','consumo consciente','hidratação','água',
  'jejum intermitente','emagrecimento','sobrepeso','obesidade','peso ideal','compulsão alimentar','transtornos alimentares',
  'anorexia','bulimia','avaliação nutricional','exame antropométrico','bioimpedância','percentual de gordura',
  'massa muscular','digestão','absorção de nutrientes','índice glicêmico','refeição','lanche saudável','café da manhã',
  'almoço','jantar','lanches','planejamento alimentar','educação nutricional','gastronomia saudável','comida de verdade',
  'comida caseira','modismo alimentar','dietas restritivas','equilíbrio nutricional','suco detox','reposição vitamínica',
  'funcionalidade alimentar','nutrigenômica','epigenética','probióticos','prebióticos','fermentados','flora intestinal',
  'microbiota','gordura corporal','metas nutricionais','orientação alimentar','terapia nutricional','comida','nutrir', 'nutrindo', 'nutricionar', 'nutricionando', 'alimentar', 'alimentando', 'dietar', 'dietando', 'saudar', 'saudando',
    'reeducar', 'reeducando', 'nutriar', 'nutriando', 'vitaminar', 'vitaminando', 'minerar', 'minerando', 'caloriar', 'caloriando',
    'carboidratar', 'carboidratando', 'proteinar', 'proteinando', 'gordurar', 'gordurando', 'fibrar', 'fibrando', 'açucarar', 'açucarando',
    'colesterolar', 'colesterolando', 'metabolizar', 'metabolizando', 'restringir', 'restringindo', 'cardapizar', 'cardapizando', 'planar', 'planando',
    'intolerar', 'intolerando', 'glutenizar', 'glutenizando', 'lactosar', 'lactosando', 'insulinar', 'insulinando', 'glicosar', 'glicosando',
    'naturalizar', 'naturalizando', 'processar', 'processando', 'suplementar', 'suplementando', 'suplementear', 'suplementeando', 'wheyar', 'wheyando',
    'creatinar', 'creatinando', 'omegar', 'omegando', 'fitoterapizar', 'fitoterapizando', 'balancear', 'balanceando', 'saudabilizar', 'saudabilizando',
    'vegetarianizar', 'vegetarianizando', 'veganizar', 'veganizando', 'integrar', 'integrando', 'organicar', 'organicando', 'conservar', 'conservando',
    'corar', 'corando', 'aditivar', 'aditivando', 'esportivizar', 'esportivizando', 'clinicar', 'clinicando', 'funcionar', 'funcionando',
    'infantilizar', 'infantilizando', 'hospitalizar', 'hospitalizando', 'escolarizar', 'escolarizando', 'coletivizar', 'coletivizando', 'piramidar', 'piramidando'
];

return [
    'Tecnologia' => $tecnologia,
    'Saúde' => $saude,
    'Design' => $design,
    'Artes' => $artes,
    'Engenharia' => $engenharia,
    'Esportes' => $esportes,
    'Ciências' => $ciencias,
    'Línguas' => $linguas,
    'Administração' => $administracao,
    'Marketing' => $marketing,
    'nutrição'=>$nutricao
];
